/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.14.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.github.ranjitsoni.moviebooking.controller;

import io.github.ranjitsoni.moviebooking.dto.BookingRequest;
import io.github.ranjitsoni.moviebooking.dto.BookingResponse;
import io.github.ranjitsoni.moviebooking.util.ApiUtil;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import java.util.Optional;

@RestController
public class BookingController {

    protected Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /bookings : Create a new booking
     * Book tickets for a specific show.
     *
     * @param bookingRequest  (required)
     * @return Booking created successfully (status code 201)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/bookings",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    public ResponseEntity<BookingResponse> createBooking(@Valid @RequestBody BookingRequest bookingRequest) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : { \"numberOfSeats\" : 0, \"bookingTime\" : \"2000-01-23T04:56:07.000+00:00\", \"showId\" : \"showId\", \"id\" : \"id\", \"userId\" : \"userId\" }, \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    /**
     * GET /bookings/{bookingId} : Get booking details
     * Retrieve detailed information about a specific booking by its ID.
     *
     * @param bookingId  (required)
     * @return Booking details (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/bookings/{bookingId}",
        produces = { "application/json" }
    )
    public ResponseEntity<BookingResponse> getBookingById(@PathVariable("bookingId") String bookingId) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : { \"numberOfSeats\" : 0, \"bookingTime\" : \"2000-01-23T04:56:07.000+00:00\", \"showId\" : \"showId\", \"id\" : \"id\", \"userId\" : \"userId\" }, \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
}
