/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.14.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.github.ranjitsoni.moviebooking.controller;

import io.github.ranjitsoni.moviebooking.dto.PaymentRequest;
import io.github.ranjitsoni.moviebooking.dto.PaymentResponse;
import io.github.ranjitsoni.moviebooking.util.ApiUtil;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import java.util.Optional;

@RestController
public class PaymentController {

    protected Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /payments : Process a payment
     * Process a payment for a specific booking.
     *
     * @param paymentRequest  (required)
     * @return Payment processed successfully (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/payments",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    public ResponseEntity<PaymentResponse> processPayment(@Valid @RequestBody PaymentRequest paymentRequest) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"amount\" : 0.8008282, \"transactionReference\" : \"transactionReference\", \"paymentId\" : \"paymentId\", \"currency\" : \"currency\", \"bookingId\" : \"bookingId\", \"status\" : \"status\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
}
