/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.14.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.github.ranjitsoni.moviebooking.controller;

import io.github.ranjitsoni.moviebooking.dto.ShowRequest;
import io.github.ranjitsoni.moviebooking.dto.ShowResponse;
import io.github.ranjitsoni.moviebooking.util.ApiUtil;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import java.util.Optional;

@RestController
public class ShowController {

    protected Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /shows : Create a new show
     * Schedule a new show for a specific movie in a specific theatre.
     *
     * @param showRequest  (required)
     * @return Show created successfully (status code 201)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/shows",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    public ResponseEntity<ShowResponse> createShow(@Valid @RequestBody ShowRequest showRequest) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : { \"availableSeats\" : 0, \"movieId\" : \"movieId\", \"startTime\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"endTime\" : \"2000-01-23T04:56:07.000+00:00\" }, \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
}
