/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.14.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.github.ranjitsoni.moviebooking.controller;

import io.github.ranjitsoni.moviebooking.dto.TheatreResponse;
import io.github.ranjitsoni.moviebooking.util.ApiUtil;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;

@RestController
public class TheatreController {

    protected Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /theatres/{theatreName} : Get a theatre by name
     * Retrieve detailed information about a specific theatre by its name.
     *
     * @param theatreName  (required)
     * @return Theatre details (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/theatres/{theatreName}",
        produces = { "application/json" }
    )
    public ResponseEntity<TheatreResponse> getTheatreByName(@PathVariable("theatreName") String theatreName) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : [ { \"shows\" : [ { \"data\" : { \"availableSeats\" : 0, \"movieId\" : \"movieId\", \"startTime\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"endTime\" : \"2000-01-23T04:56:07.000+00:00\" }, \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] }, { \"data\" : { \"availableSeats\" : 0, \"movieId\" : \"movieId\", \"startTime\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"endTime\" : \"2000-01-23T04:56:07.000+00:00\" }, \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] } ], \"name\" : \"name\", \"location\" : \"location\", \"id\" : \"id\" }, { \"shows\" : [ { \"data\" : { \"availableSeats\" : 0, \"movieId\" : \"movieId\", \"startTime\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"endTime\" : \"2000-01-23T04:56:07.000+00:00\" }, \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] }, { \"data\" : { \"availableSeats\" : 0, \"movieId\" : \"movieId\", \"startTime\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"endTime\" : \"2000-01-23T04:56:07.000+00:00\" }, \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] } ], \"name\" : \"name\", \"location\" : \"location\", \"id\" : \"id\" } ], \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    /**
     * GET /theatres/{movieId} : Get theatres showing a specific movie
     * Retrieve a list of theaters that are currently showing a specific movie by its ID.
     *
     * @param movieId  (required)
     * @return Theatre details (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/theatres/{movieId}",
        produces = { "application/json" }
    )
    public ResponseEntity<TheatreResponse> getTheatresByMovieId(@PathVariable("movieId") String movieId) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : [ { \"shows\" : [ { \"data\" : { \"availableSeats\" : 0, \"movieId\" : \"movieId\", \"startTime\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"endTime\" : \"2000-01-23T04:56:07.000+00:00\" }, \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] }, { \"data\" : { \"availableSeats\" : 0, \"movieId\" : \"movieId\", \"startTime\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"endTime\" : \"2000-01-23T04:56:07.000+00:00\" }, \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] } ], \"name\" : \"name\", \"location\" : \"location\", \"id\" : \"id\" }, { \"shows\" : [ { \"data\" : { \"availableSeats\" : 0, \"movieId\" : \"movieId\", \"startTime\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"endTime\" : \"2000-01-23T04:56:07.000+00:00\" }, \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] }, { \"data\" : { \"availableSeats\" : 0, \"movieId\" : \"movieId\", \"startTime\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"endTime\" : \"2000-01-23T04:56:07.000+00:00\" }, \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] } ], \"name\" : \"name\", \"location\" : \"location\", \"id\" : \"id\" } ], \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
}
