/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.14.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.github.ranjitsoni.moviebooking.controller;

import io.github.ranjitsoni.moviebooking.dto.UserRequest;
import io.github.ranjitsoni.moviebooking.dto.UserResponse;
import io.github.ranjitsoni.moviebooking.util.ApiUtil;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import java.util.Optional;

@RestController
public class UserController {

    protected Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /users : Create a new user
     * Register a new user in the system.
     *
     * @param userRequest  (required)
     * @return User created successfully (status code 201)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/users",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    public ResponseEntity<UserResponse> createUser(@Valid @RequestBody UserRequest userRequest) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : { \"phone\" : \"phone\", \"name\" : \"name\", \"id\" : \"id\", \"email\" : \"email\" }, \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        System.out.println("UserApi.createUser() called with userRequest: " + userRequest);
        return new ResponseEntity<>(HttpStatus.OK);
    }

    /**
     * GET /users/{userId} : Get user details
     * Retrieve detailed information about a specific user by their ID.
     *
     * @param userId  (required)
     * @return User details (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/users/{userId}",
        produces = { "application/json" }
    )
    public ResponseEntity<UserResponse> getUserById(@PathVariable("userId") String userId) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : { \"phone\" : \"phone\", \"name\" : \"name\", \"id\" : \"id\", \"email\" : \"email\" }, \"notifications\" : [ { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" }, { \"code\" : \"code\", \"type\" : \"type\", \"message\" : \"message\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
}
